In [37]:
import numpy as np
from utils import round_to_array

# Example arrays
# a = np.random.random(size=(3,5))
a = np.random.random(size=(3,3)).round(1)
b = np.array([0., 0.5, 1.0])

# Find the index in b of the closest value for each value in a
closest_indices = np.abs(a[:, None] - b).argmin(axis=-1)
# Replace each entry in a with the closest entry from b
a_closest = b[closest_indices]
print(a)
print(a_closest)
print(round_to_array(a,b)) # Output: [1. 3. 3. 5.]

[[1.  0.4 0.5]
 [0.7 0.3 0.3]
 [0.4 0.5 0.7]]
[[0.5]
 [0.5]
 [0.5]]
[[1.  0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [41]:
unique_values, indices = np.unique(a, return_inverse=True)


In [ ]:
indices = indices.reshape(a.shape)

In [47]:
indices

array([[4, 1, 2],
       [3, 0, 0],
       [1, 2, 3]])

In [77]:
a

array([[1. , 0.4, 0.5],
       [0.7, 0.3, 0.3],
       [0.4, 0.5, 0.7]])

In [79]:
a[np.where(indices == 4)].sum()

1.0

In [80]:
[a[np.where(indices == index)].sum() for index in range(indices.max()+1)]

[0.6, 0.8, 1.0, 1.4, 1.0]

In [73]:
np.where(indices == 4)

(array([0]), array([0]))

In [65]:
a

array([[1. , 0.4, 0.5],
       [0.7, 0.3, 0.3],
       [0.4, 0.5, 0.7]])

In [62]:
range(indices.max()+1)

range(0, 5)

In [61]:
indices.max()

4